### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by redstealth** [victorfisac/DriftWorld#2]
hello thanks for sharing this project please can you show us how we can resolve those issues

Assets/Resources/Scripts/Multiplayer/CustomNetworkManager.cs(52,40): error CS0246: The type or namespace name `CreateMatchResponse' could not be found. Are you missing a using directive or an assembly reference?

Assets/Resources/Scripts/Multiplayer/CustomNetworkManager.cs(59,37): error CS0246: The type or namespace name `JoinMatchResponse' could not be found. Are you missing a using directive or an assembly reference?

Assets/Resources/Scripts/Multiplayer/CustomNetworkManager.cs(66,29): error CS0246: The type or namespace name `BasicResponse' could not be found. Are you missing a using directive or an assembly reference?

Assets/Resources/Scripts/Multiplayer/CustomNetworkManager.cs(89,34): error CS0246: The type or namespace name `BasicResponse' could not be found. Are you missing a using directive or an assembly reference?

**Comment by victorfisac** [comment]
Hi @redstealth. This project is developed with a old Unity version. Some source code changed giving you those errors... I didn't updated the project after finished it some time ago.

**Comment by redstealth** [comment]
ok thanks verry much


2016-12-11 19:52 GMT+00:00 Víctor Fisac <notifications@github.com>:
